### ISSUE TITLE
npm modules install on Phoenix Framework

### ISSUE THREAD

**Issue by kaave** [ali-inc/ubuntu15.04-elixir#5]
いくつかnpmモジュールを入れておいて頂けるとはかどります。

|モジュール|説明|
|---|---|
|coffee-script|言わずもがな|
|typescript|言わずもがな|
|babel|言わずもがな|
|babel-cli|言わずもがな ↑があればいらんかも|
|tsd|TypeScriptの型定義ファイル管理|
|dtsm|TypeScriptの型定義ファイル管理 こっちのほうが↑よりいいかな|
|jade|言わずもがな|
|gulp|言わずもがな|
|eslint|JavaScriptのlinter 拡張性に優れるため2015/12現在のベスト|
|coffeelint|CoffeeScriptのlinter|
|tslint|TypeScriptのlinter|
|typescript-tools|忘れました エディタと連携してゴニョゴニョかな・・・|
|csslint|CSSのlinter stylelintのほうが流行ってる？あんまわかりません|
|node-inspector|忘れましたが諸々でいるはず|
|karma-cli|JavaScriptテストランナー|

この辺のは副作用もないでしょうし是非。

**Comment by kaave** [comment]
以下のコードでいかがでしょう。一応動きました。

```
# install node.js modules
- name: install npm plugins
  npm: name={{ item }} global=yes executable=/home/vagrant/.anyenv/envs/ndenv/shims/npm
  with_items:
    - coffee-script
    - typescript
    - babel
    - babel-cli
    - tsd
    - dtsm
    - gulp
    - eslint
    - coffeelint
    - tslint
    - typescript-tools
    - csslint
    - karma-cli
```
